linters-settings:
  funlen:
    lines: -1
    statements: 60
  gci:
    sections:
      - standard
      - default
      - prefix(quartr-cli)
    skip-generated: true
    custom-order: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - singleCaseSwitch
      - unnamedResult
      - whyNoLint
  gocyclo:
    min-complexity: 15
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-no-explanation: []
    require-explanation: false
    require-specific: false
  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - inamedparam
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint

issues:
  max-same-issues: 10

run:
  timeout: 3m
  go: '1.26'
