repos:
  - repo: https://github.com/golangci/golangci-lint.git
    rev: v2.12.0
    hooks:
      - id: golangci-lint
        args: [--fix]
  - repo: local
    hooks:
      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        types: [go]
        pass_filenames: false
        require_serial: true
